# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chatgpt2dlg',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/chatgpt2dlg',
                'lib_path': 'chatgpt2dlg'},
  'syms': { 'chatgpt2dlg.core': { 'chatgpt2dlg.core._api_path': ('core.html#_api_path', 'chatgpt2dlg/core.py'),
                                  'chatgpt2dlg.core._content': ('core.html#_content', 'chatgpt2dlg/core.py'),
                                  'chatgpt2dlg.core._is_convo': ('core.html#_is_convo', 'chatgpt2dlg/core.py'),
                                  'chatgpt2dlg.core._ref_md': ('core.html#_ref_md', 'chatgpt2dlg/core.py'),
                                  'chatgpt2dlg.core._splice_refs': ('core.html#_splice_refs', 'chatgpt2dlg/core.py'),
                                  'chatgpt2dlg.core.convo2dlg': ('core.html#convo2dlg', 'chatgpt2dlg/core.py'),
                                  'chatgpt2dlg.core.convo_nodes': ('core.html#convo_nodes', 'chatgpt2dlg/core.py'),
                                  'chatgpt2dlg.core.nodes2chat': ('core.html#nodes2chat', 'chatgpt2dlg/core.py'),
                                  'chatgpt2dlg.core.url2convo': ('core.html#url2convo', 'chatgpt2dlg/core.py')}}}
