# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chatgpt2dialog',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/chatgpt2dialog',
                'lib_path': 'chatgpt2dialog'},
  'syms': { 'chatgpt2dialog.core': { 'chatgpt2dialog.core._api_path': ('core.html#_api_path', 'chatgpt2dialog/core.py'),
                                     'chatgpt2dialog.core._content': ('core.html#_content', 'chatgpt2dialog/core.py'),
                                     'chatgpt2dialog.core._is_convo': ('core.html#_is_convo', 'chatgpt2dialog/core.py'),
                                     'chatgpt2dialog.core._ref_md': ('core.html#_ref_md', 'chatgpt2dialog/core.py'),
                                     'chatgpt2dialog.core._splice_refs': ('core.html#_splice_refs', 'chatgpt2dialog/core.py'),
                                     'chatgpt2dialog.core.convo2dlg': ('core.html#convo2dlg', 'chatgpt2dialog/core.py'),
                                     'chatgpt2dialog.core.convo_nodes': ('core.html#convo_nodes', 'chatgpt2dialog/core.py'),
                                     'chatgpt2dialog.core.nodes2chat': ('core.html#nodes2chat', 'chatgpt2dialog/core.py'),
                                     'chatgpt2dialog.core.url2convo': ('core.html#url2convo', 'chatgpt2dialog/core.py')}}}
